### ISSUE TITLE
APL "NOOPT" build fails due to compiler intrinsic functions

### ISSUE THREAD

**Issue by mmustafa88** [slimbootloader/slimbootloader#875] opened 2020-10-14 09:26 UTC
When build for APL with "NOOPT" flag, the build fails. Please find below errors:

NvmExpressLib.lib(NvmExpressPassthru.obj) : error LNK2001: unresolved external symbol __aullshr
TimeStampLib.lib(TimeStampLib.obj) : error LNK2001: unresolved external symbol __aullshr
IppCryptoLib.lib(pcpbnu32arith.obj) : error LNK2001: unresolved external symbol __aullshr
IppCryptoLib.lib(pcpsm3ca.obj) : error LNK2001: unresolved external symbol __allshl
IppCryptoLib.lib(pcpsha512ca.obj) : error LNK2001: unresolved external symbol __allshl
IppCryptoLib.lib(pcpsha256ca.obj) : error LNK2001: unresolved external symbol __allshl
IppCryptoLib.lib(pcpbnu32arith.obj) : error LNK2001: unresolved external symbol __allshl

**Comment by mauricema** [comment] 2020-10-14 15:54
Please check PR#876.   Please note, that patch will only address compiling issue caused by compiler intrinsic functions.

**Comment by rprangar** [comment] 2020-10-15 16:39
Please close the issue if the build issue is resolved.

Thanks.

**Comment by mmustafa88** [comment] 2020-10-16 06:55
Fixed.

**Closed** 2020-10-16 06:54 UTC
